source/accounts/urls.py
from django.contrib.auth.views import LoginView, LogoutView
from django.urls import path

from accounts.views import RegisterView, ProfileView, ChangeProfileView, ChangePasswordView

app_name = "accounts"

urlpatterns = [
    path('login/', LoginView.as_view(template_name="login.html"), name="login"),
    path('logout/', LogoutView.as_view(), name="logout"),
    path('registration/', RegisterView.as_view(), name="registration"),
    path('<int:pk>/', ProfileView.as_view(), name="profile"),
    path('<int:pk>/change/', ChangeProfileView.as_view(), name="change_profile"),
    path('change/password/', ChangePasswordView.as_view(), name="change_password"),
]

source/review/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('webapp.urls')),
    path('accounts/', include('accounts.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

source/accounts/models.py
from django.contrib.auth import get_user_model
from django.db import models


class Profile(models.Model):
    birthday = models.DateField(null=True, blank=True, verbose_name="Дата рождения")
    avatar = models.ImageField(upload_to="avatars", null=True, blank=True, verbose_name="Аватар")
    user = models.OneToOneField(get_user_model(),
                                on_delete=models.CASCADE,
                                verbose_name="Пользователь",
                                related_name="profile")

source/accounts/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth import get_user_model

from accounts.models import Profile


class MyUserCreationForm(UserCreationForm):
    email = forms.EmailField(required=True)

    class Meta(UserCreationForm.Meta):
        fields = ['username', 'password1', 'password2', 'first_name', 'last_name', 'email']


class UserChangeForm(forms.ModelForm):
    email = forms.EmailField(required=True)

    class Meta:
        model = get_user_model()
        fields = ['first_name', 'last_name', 'email']
        labels = {'first_name': 'Имя', 'last_name': 'Фамилия', 'email': 'Email'}


class ProfileChangeForm(forms.ModelForm):
    class Meta:
        model = Profile
        fields = ['birthday', 'avatar']


class PasswordChangeForm(forms.ModelForm):
    password = forms.CharField(label="Новый пароль", strip=False, widget=forms.PasswordInput)
    password_confirm = forms.CharField(label="Подтвердите пароль", widget=forms.PasswordInput, strip=False)
    old_password = forms.CharField(label="Старый пароль", strip=False, widget=forms.PasswordInput)

    def clean_password_confirm(self):
        password = self.cleaned_data.get("password")
        password_confirm = self.cleaned_data.get("password_confirm")
        if password and password_confirm and password != password_confirm:
            raise forms.ValidationError('Пароли не совпадают!')
        return password_confirm

    def clean_old_password(self):
        old_password = self.cleaned_data.get('old_password')
        if not self.instance.check_password(old_password):
            raise forms.ValidationError('Старый пароль неправильный!')
        return old_password

    def save(self, commit=True):
        user = self.instance
        user.set_password(self.cleaned_data["password"])
        if commit:
            user.save()
        return user

    class Meta:
        model = get_user_model()
        fields = ['password', 'password_confirm', 'old_password']

source/accounts/views.py
from django.contrib.auth import login, get_user_model, update_session_auth_hash
from django.contrib.auth.mixins import PermissionRequiredMixin
from django.shortcuts import redirect
from django.urls import reverse
from django.views.generic import CreateView, DetailView, UpdateView

from accounts.forms import MyUserCreationForm, UserChangeForm, ProfileChangeForm, PasswordChangeForm
from accounts.models import Profile


class RegisterView(CreateView):
    model = get_user_model()
    template_name = 'registration.html'
    form_class = MyUserCreationForm

    def form_valid(self, form):
        user = form.save()
        Profile.objects.create(user=user)
        login(self.request, user)
        return redirect(self.get_success_url())

    def get_success_url(self):
        next_url = self.request.GET.get('next')
        if not next_url:
            next_url = self.request.POST.get('next')
        if not next_url:
            next_url = reverse('webapp:index')
        return next_url


class ProfileView(DetailView):
    model = get_user_model()
    template_name = "profile.html"
    paginate_by = 3
    context_object_name = "user_obj"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        reviews = self.object.reviews.all()
        if not self.request.user.has_perm("webapp.review_not_moderated") and self.object != self.request.user:
            reviews = reviews.filter(is_moderated=True)
        context['reviews'] = reviews.order_by("-updated_at")
        return context


class ChangeProfileView(PermissionRequiredMixin, UpdateView):
    model = get_user_model()
    form_class = UserChangeForm
    template_name = "change_user.html"
    profile_form_class = ProfileChangeForm
    context_object_name = "user_obj"

    def has_permission(self):
        return self.request.user == self.get_object()

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        if "profile_form" not in context:
            context["profile_form"] = self.profile_form_class(instance=self.get_object().profile)
        return context

    def post(self, request, *args, **kwargs):
        self.object = self.get_object()
        form = self.form_class(instance=self.object, data=request.POST)
        profile_form = self.profile_form_class(instance=self.object.profile,
                                               data=request.POST,
                                               files=request.FILES)
        if form.is_valid():
            return self.form_valid(form, profile_form)
        else:
            return self.form_invalid(form, profile_form)

    def form_valid(self, form, profile_form):
        form.save()
        profile_form.save()
        return redirect("accounts:profile", self.object.pk)

    def form_invalid(self, form, profile_form):
        return self.render_to_response(self.get_context_data(form=form, profile_form=profile_form))


class ChangePasswordView(UpdateView):
    model = get_user_model()
    form_class = PasswordChangeForm
    template_name = "change_password.html"

    def get_object(self, queryset=None):
        return self.request.user

    def get_success_url(self):
        return reverse("accounts:profile", kwargs={"pk": self.request.user.pk})

    def form_valid(self, form):
        result = super().form_valid(form)
        update_session_auth_hash(self.request, self.object)
        return result

source/accounts/templates/change_password.html
{% extends "base.html" %}

{% block title %}
    Изменить пароль
{% endblock %}

{% block content %}
    <div class="text-center">
        <h1>Изменить пароль</h1>
        <form action="" method="post">
            {% include "partial/form.html" with button_text="Изменить" %}
        </form>
    </div>
{% endblock %}

source/accounts/templates/change_user.html
{% extends "base.html" %}

{% block title %}
    Редактировать профиль
{% endblock %}

{% block content %}
    <div class="text-center">
        <h1>Редактировать профиль</h1>
        <form action="" method="post" enctype="multipart/form-data">
            {% include "partial/form.html" with fields_only=True %}
            {% include "partial/form.html" with form=profile_form button_text="Редактировать"%}
        </form>
    </div>
{% endblock %}

source/accounts/templates/login.html
{% extends "base.html" %}

{% block title %}
    Аутентификация
{% endblock %}

{% block content %}
    <h1>Аутентификация</h1>
    <div class="text-center">
        <form method="post" class="w-50 ms-auto me-auto">
            {% csrf_token %}
            {% if has_error %}
                <p class="text-danger">Неверное имя пользователя или пароль!</p>
            {% endif %}
            <div class="form-group">
                <label for="username" class="form-label">Имя пользователя:</label>
                <input type="text" name="username" class="form-control" id="username">
            </div>
            <div class="form-group">
                <label for="password" class="form-label">Пароль:</label>
                <input type="password" name="password" class="form-control" id="password">
            </div>
            <button class="mt-3 btn btn-outline-dark" type="submit">Войти</button>
        </form>
    </div>
{% endblock %}

source/accounts/templates/profile.html
{% extends "base.html" %}

{% block title %}
    Профиль пользователя
{% endblock %}

{% block nav %}
    {% if user_obj == user %}
        <li class="nav-item">
            <a class="nav-link" href="{% url 'accounts:change_profile' user_obj.pk %}">Редактировать</a>
        </li>
        <li class="nav-item">
            <a class="nav-link" href="{% url 'accounts:change_password' %}">Сменить пароль</a>
        </li>
    {% endif %}
{% endblock %}

{% block content %}
    <div class="card flex-row mt-3">
        {% if user_obj.profile.avatar %}
            <img src="{{ user_obj.profile.avatar.url }}" class="card-img-top w-25" alt="...">
        {% endif %}
        <div class="card-body ms-5">
            <h5 class="card-title">Имя пользователя: {{ user_obj.username }}</h5>
            <h6 class="card-subtitle mb-2 text-muted">Год рождения: {{ user_obj.profile.birthday }}</h6>
            <h6 class="card-subtitle mb-2 text-muted">Имя: {{ user_obj.first_name }}</h6>
            <h6 class="card-subtitle mb-2 text-muted">Фамилия: {{ user_obj.last_name }}</h6>
            <h6 class="card-subtitle mb-2 text-muted">Почта: {{ user_obj.email }}</h6>
        </div>
    </div>
    {% include "partial/reviews_list.html" %}
{% endblock %}

source/accounts/templates/registration.html
{% extends "base.html" %}

{% block title %}
    Регистрация пользователя
{% endblock %}

{% block content %}
    <h1>Регистрация</h1>

    <form method="post">
    {% include 'partial/form.html' with button_text='Зарегистрироваться' %}
    </form>
{% endblock %}