source/review/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('webapp.urls')),
    path('accounts/', include('accounts.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

source/webapp/urls.py
from django.urls import path

from webapp.views import IndexView, ProductCreateView, ProductDetailView, ProductUpdateView, ProductDeleteView
from webapp.views import ReviewCreateView, ReviewUpdateView, ReviewDeleteView, NotModeratedReview

app_name = "webapp"

urlpatterns = [
    path('', IndexView.as_view(), name="index"),
    path('products/add/', ProductCreateView.as_view(), name="create_product"),
    path('products/<int:pk>/', ProductDetailView.as_view(), name="product_view"),
    path('products/<int:pk>/update/', ProductUpdateView.as_view(), name="update_product"),
    path('products/<int:pk>/delete/', ProductDeleteView.as_view(), name="delete_product"),
    path('products/<int:pk>/review/add/', ReviewCreateView.as_view(), name="review_create"),
    path('reviews/<int:pk>/update/', ReviewUpdateView.as_view(), name="update_review"),
    path('reviews/<int:pk>/delete/', ReviewDeleteView.as_view(), name="delete_review"),
    path('reviews/no-moderation/', NotModeratedReview.as_view(), name="not_moderated_reviews"),
]

source/webapp/models.py
from django.contrib.auth import get_user_model
from django.db import models
from django.core.validators import MaxValueValidator, MinValueValidator
from django.db.models import Avg

CHOICES = [('others', 'Другое'), ('fast-food', 'Фаст-фуд'), ('drinks', 'Напитки'), ('sweets', 'Сладости')]


class Product(models.Model):
    name = models.CharField(max_length=60, verbose_name='Название')
    category = models.CharField(max_length=30, default='others', choices=CHOICES, verbose_name='Категория')
    description = models.TextField(max_length=1000, null=True, blank=True, verbose_name='Описание')
    picture = models.ImageField(upload_to='pictures', null=True, blank=True, verbose_name='Картинка')

    class Meta:
        db_table = "products"
        verbose_name = "Товар"
        verbose_name_plural = "Товары"

    def __str__(self):
        return f"{self.name} - {self.category}"

    def get_avg_mark(self):
        result = self.reviews.filter(is_moderated=True).aggregate(avg=Avg("mark"))
        return result["avg"]


class Review(models.Model):
    author = models.ForeignKey(get_user_model(), on_delete=models.CASCADE, related_name='reviews', verbose_name='Автор')
    product = models.ForeignKey('webapp.Product', on_delete=models.CASCADE, related_name='reviews',
                                verbose_name='Товар')
    text = models.TextField(max_length=1500, verbose_name='Текст отзыва')
    mark = models.IntegerField(verbose_name='Оценка', validators=[MinValueValidator(1), MaxValueValidator(5)])
    is_moderated = models.BooleanField(verbose_name='Прошел модерацию', default=False)
    created_at = models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')
    updated_at = models.DateTimeField(auto_now=True, verbose_name='Дата изменения')

    class Meta:
        db_table = "reviews"
        verbose_name = "Отзыв"
        verbose_name_plural = "Отзывы"
        permissions = [("review_not_moderated", "Просмотр немодерированных отзывов")]

    def __str__(self):
        return f"{self.pk}: {self.author.username} - {self.product.name}"

source/webapp/forms.py
from django import forms

from webapp.models import Product, Review
from django.forms import widgets


class ProductForm(forms.ModelForm):
    class Meta:
        model = Product
        fields = ["name", "description", "category", "picture"]
        widgets = {"description": widgets.Textarea}


class ReviewModeratorForm(forms.ModelForm):
    class Meta:
        model = Review
        fields = ["text", "mark", "is_moderated"]
        widgets = {"text": widgets.Textarea}


class ReviewUserForm(forms.ModelForm):
    class Meta:
        model = Review
        fields = ["text", "mark"]
        widgets = {"text": widgets.Textarea}

source/webapp/views/products.py
from django.urls import reverse_lazy, reverse
from django.views.generic import ListView, DetailView, CreateView, UpdateView, DeleteView
from django.contrib.auth.mixins import PermissionRequiredMixin

from webapp.models import Product
from webapp.forms import ProductForm


class IndexView(ListView):
    model = Product
    template_name = "products/index.html"
    context_object_name = "products"
    paginate_by = 3


class ProductDetailView(DetailView):
    template_name = "products/detail.html"
    model = Product

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        reviews = self.object.reviews.all()
        if not self.request.user.has_perm("webapp.review_not_moderated"):
            reviews = reviews.filter(is_moderated=True)
        context['reviews'] = reviews.order_by("-updated_at")
        return context


class ProductCreateView(CreateView):
    form_class = ProductForm
    template_name = "products/create.html"

    def get_success_url(self):
        return reverse("webapp:product_view", kwargs={"pk": self.object.pk})


class ProductUpdateView(PermissionRequiredMixin, UpdateView):
    form_class = ProductForm
    template_name = "products/update.html"
    model = Product
    permission_required = "webapp.change_product"

    def get_success_url(self):
        return reverse("webapp:product_view", kwargs={"pk": self.object.pk})


class ProductDeleteView(PermissionRequiredMixin, DeleteView):
    model = Product
    template_name = "products/delete.html"
    success_url = reverse_lazy('webapp:index')
    permission_required = "webapp.delete_product"

source/webapp/views/reviews.py
from django.contrib.auth.mixins import LoginRequiredMixin, PermissionRequiredMixin
from django.urls import reverse
from django.views.generic import CreateView, UpdateView, DeleteView, ListView
from django.shortcuts import get_object_or_404

from webapp.forms import ReviewUserForm, ReviewModeratorForm
from webapp.models import Product, Review


class ReviewCreateView(LoginRequiredMixin, CreateView):
    form_class = ReviewUserForm
    template_name = "reviews/create.html"

    def form_valid(self, form):
        product = get_object_or_404(Product, pk=self.kwargs.get("pk"))
        author = self.request.user
        form.instance.author = author
        form.instance.product = product
        return super().form_valid(form)

    def get_success_url(self):
        return reverse("webapp:product_view", kwargs={"pk": self.object.product.pk})


class ReviewUpdateView(PermissionRequiredMixin, UpdateView):
    form_class = ReviewUserForm
    template_name = "reviews/update.html"
    permission_required = "webapp.change_review"
    model = Review

    def get_form_class(self):
        if self.request.user.has_perm("webapp.change_review"):
            return ReviewModeratorForm
        return ReviewUserForm

    def has_permission(self):
        return super().has_permission() or self.get_object().author == self.request.user

    def get_success_url(self):
        return reverse("webapp:product_view", kwargs={"pk": self.object.product.pk})


class ReviewDeleteView(PermissionRequiredMixin, DeleteView):
    permission_required = "webapp.change_review"
    model = Review

    def get(self, request, *args, **kwargs):
        return self.delete(request, *args, **kwargs)

    def has_permission(self):
        return super().has_permission() or self.get_object().author == self.request.user

    def get_success_url(self):
        return reverse("webapp:product_view", kwargs={"pk": self.object.product.pk})


class NotModeratedReview(PermissionRequiredMixin, ListView):
    queryset = Review.objects.filter(is_moderated=False)
    context_object_name = "reviews"
    template_name = "reviews/not_moderated.html"
    ordering = ['-updated_at']
    permission_required = "webapp.review_not_moderated"

source/webapp/templates/partial/form.html
{% if not fields_only %}
    {% csrf_token %}
{% endif %}

{% for error in form.non_field_errors %}
    <p class="text-danger">{{ error }}</p>
{% endfor %}

{% for field in form %}
    <p><label for="{{ field.id_for_label }}">{{ field.label }}</label></p>
    {% for error in field.errors %}
        <p class="text-danger">{{ error }}</p>
    {% endfor %}
    <p>{{ field }}</p>
{% endfor %}

{% if not fields_only %}
    <input type="submit" value="{{ button_text }}"/>
{% endif %}

source/webapp/templates/partial/pagination.html
<ul class="pagination mt-3 justify-content-center">
    <li class="page-item">
        <a class="page-link" href="?page=1{% if query %}&{{ query }}{% endif %}">Начало</a>
    </li>
    {% if page_obj.has_previous %}
        <li class="page-item">
            <a class="page-link" href="?page={{ page_obj.previous_page_number }}{% if query %}&{{ query }}{% endif %}">Предыдущая</a>
        </li>
        <li class="page-item">
            <a class="page-link"
               href="?page=
                       {{ page_obj.previous_page_number }}{% if query %}&{{ query }}{% endif %}">{{ page_obj.previous_page_number }}</a>
        </li>
    {% else %}
        <li class="page-item disabled">
            <a class="page-link" href="#" tabindex="-1" aria-disabled="true">Предыдущая</a>
        </li>
    {% endif %}

    <li class="page-item">
        <form method="get">
            <label for="page">
                <input class="form-control rounded-0" type="text" name="page" id="page" value="{{ page_obj.number }}">
            </label>
            {% if  search%}
            <label>
                <input class="form-control" hidden type="text" name="search" value="{{ search }}">
            </label>
            {% endif %}
        </form>
    </li>

    {% if page_obj.has_next %}
        <li class="page-item">
            <a class="page-link"
               href="?page=
                       {{ page_obj.next_page_number }}{% if query %}&{{ query }}{% endif %}">{{ page_obj.next_page_number }}</a>
        </li>
        <li class="page-item">
            <a class="page-link"
               href="?page={{ page_obj.next_page_number }}{% if query %}&{{ query }}{% endif %}">Следующая</a>
        </li>
    {% else %}
        <li class="page-item disabled">
            <a class="page-link" href="#" tabindex="-1" aria-disabled="true">Следующая</a>
        </li>
    {% endif %}
    <li class="page-item">
        <a class="page-link" href="?page={{ page_obj.paginator.num_pages }}{% if query %}&{{ query }}{% endif %}">В
            конец</a>
    </li>
</ul>

source/webapp/templates/partial/reviews_list.html
<h1 class="text-center">Отзывы</h1>
<div class="row">
    {% for review in reviews %}
        <div class="col-12 col-md-6 col-lg-4">
            <div class="card mb-3">
                <div class="card-body">
                    <h5 class="card-title">{{ review.mark }} <span>{{ review.author.username }}|
                        {{ review.author.email }}</span></h5>
                </div>
                <div>
                    <p>{{ review.text }}</p>
                </div>
                {% if review.author == request.user or perms.webapp.change_review %}
                    <a href="{% url "webapp:update_review" review.pk %}">Редактировать</a>
                {% endif %}
                {% if review.author == request.user or perms.webapp.delete_review %}
                    <a href="{% url "webapp:delete_review" review.pk %}">Удалить</a>
                {% endif %}
            </div>
        </div>
    {% empty %}
        Нету отзывов!
    {% endfor %}
</div>