source/review/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('webapp.urls')),
    path('accounts/', include('accounts.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

source/webapp/urls.py
from django.urls import path

from webapp.views import IndexView, ProductCreateView, ProductDetailView, ProductUpdateView, ProductDeleteView
from webapp.views import ReviewCreateView, ReviewUpdateView, ReviewDeleteView, NotModeratedReview

app_name = "webapp"

urlpatterns = [
    path('', IndexView.as_view(), name="index"),
    path('products/add/', ProductCreateView.as_view(), name="create_product"),
    path('products/<int:pk>/', ProductDetailView.as_view(), name="product_view"),
    path('products/<int:pk>/update/', ProductUpdateView.as_view(), name="update_product"),
    path('products/<int:pk>/delete/', ProductDeleteView.as_view(), name="delete_product"),
    path('products/<int:pk>/review/add/', ReviewCreateView.as_view(), name="review_create"),
    path('reviews/<int:pk>/update/', ReviewUpdateView.as_view(), name="update_review"),
    path('reviews/<int:pk>/delete/', ReviewDeleteView.as_view(), name="delete_review"),
    path('reviews/no-moderation/', NotModeratedReview.as_view(), name="not_moderated_reviews"),
]

source/webapp/models.py
from django.contrib.auth import get_user_model
from django.db import models
from django.core.validators import MaxValueValidator, MinValueValidator
from django.db.models import Avg

CHOICES = [('others', 'Другое'), ('fast-food', 'Фаст-фуд'), ('drinks', 'Напитки'), ('sweets', 'Сладости')]


class Product(models.Model):
    name = models.CharField(max_length=60, verbose_name='Название')
    category = models.CharField(max_length=30, default='others', choices=CHOICES, verbose_name='Категория')
    description = models.TextField(max_length=1000, null=True, blank=True, verbose_name='Описание')
    picture = models.ImageField(upload_to='pictures', null=True, blank=True, verbose_name='Картинка')

    class Meta:
        db_table = "products"
        verbose_name = "Товар"
        verbose_name_plural = "Товары"

    def __str__(self):
        return f"{self.name} - {self.category}"

    def get_avg_mark(self):
        result = self.reviews.filter(is_moderated=True).aggregate(avg=Avg("mark"))
        return result["avg"]


class Review(models.Model):
    author = models.ForeignKey(get_user_model(), on_delete=models.CASCADE, related_name='reviews', verbose_name='Автор')
    product = models.ForeignKey('webapp.Product', on_delete=models.CASCADE, related_name='reviews',
                                verbose_name='Товар')
    text = models.TextField(max_length=1500, verbose_name='Текст отзыва')
    mark = models.IntegerField(verbose_name='Оценка', validators=[MinValueValidator(1), MaxValueValidator(5)])
    is_moderated = models.BooleanField(verbose_name='Прошел модерацию', default=False)
    created_at = models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')
    updated_at = models.DateTimeField(auto_now=True, verbose_name='Дата изменения')

    class Meta:
        db_table = "reviews"
        verbose_name = "Отзыв"
        verbose_name_plural = "Отзывы"
        permissions = [("review_not_moderated", "Просмотр немодерированных отзывов")]

    def __str__(self):
        return f"{self.pk}: {self.author.username} - {self.product.name}"

source/webapp/forms.py
from django import forms

from webapp.models import Product, Review
from django.forms import widgets


class ProductForm(forms.ModelForm):
    class Meta:
        model = Product
        fields = ["name", "description", "category", "picture"]
        widgets = {"description": widgets.Textarea}


class ReviewModeratorForm(forms.ModelForm):
    class Meta:
        model = Review
        fields = ["text", "mark", "is_moderated"]
        widgets = {"text": widgets.Textarea}


class ReviewUserForm(forms.ModelForm):
    class Meta:
        model = Review
        fields = ["text", "mark"]
        widgets = {"text": widgets.Textarea}

source/webapp/views/products.py
from django.urls import reverse_lazy, reverse
from django.views.generic import ListView, DetailView, CreateView, UpdateView, DeleteView
from django.contrib.auth.mixins import PermissionRequiredMixin

from webapp.models import Product
from webapp.forms import ProductForm


class IndexView(ListView):
    model = Product
    template_name = "products/index.html"
    context_object_name = "products"
    paginate_by = 3


class ProductDetailView(DetailView):
    template_name = "products/detail.html"
    model = Product

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        reviews = self.object.reviews.all()
        if not self.request.user.has_perm("webapp.review_not_moderated"):
            reviews = reviews.filter(is_moderated=True)
        context['reviews'] = reviews.order_by("-updated_at")
        return context


class ProductCreateView(CreateView):
    form_class = ProductForm
    template_name = "products/create.html"

    def get_success_url(self):
        return reverse("webapp:product_view", kwargs={"pk": self.object.pk})


class ProductUpdateView(PermissionRequiredMixin, UpdateView):
    form_class = ProductForm
    template_name = "products/update.html"
    model = Product
    permission_required = "webapp.change_product"

    def get_success_url(self):
        return reverse("webapp:product_view", kwargs={"pk": self.object.pk})


class ProductDeleteView(PermissionRequiredMixin, DeleteView):
    model = Product
    template_name = "products/delete.html"
    success_url = reverse_lazy('webapp:index')
    permission_required = "webapp.delete_product"

source/webapp/views/reviews.py
from django.contrib.auth.mixins import LoginRequiredMixin, PermissionRequiredMixin
from django.urls import reverse
from django.views.generic import CreateView, UpdateView, DeleteView, ListView
from django.shortcuts import get_object_or_404

from webapp.forms import ReviewUserForm, ReviewModeratorForm
from webapp.models import Product, Review


class ReviewCreateView(LoginRequiredMixin, CreateView):
    form_class = ReviewUserForm
    template_name = "reviews/create.html"

    def form_valid(self, form):
        product = get_object_or_404(Product, pk=self.kwargs.get("pk"))
        author = self.request.user
        form.instance.author = author
        form.instance.product = product
        return super().form_valid(form)

    def get_success_url(self):
        return reverse("webapp:product_view", kwargs={"pk": self.object.product.pk})


class ReviewUpdateView(PermissionRequiredMixin, UpdateView):
    form_class = ReviewUserForm
    template_name = "reviews/update.html"
    permission_required = "webapp.change_review"
    model = Review

    def get_form_class(self):
        if self.request.user.has_perm("webapp.change_review"):
            return ReviewModeratorForm
        return ReviewUserForm

    def has_permission(self):
        return super().has_permission() or self.get_object().author == self.request.user

    def get_success_url(self):
        return reverse("webapp:product_view", kwargs={"pk": self.object.product.pk})


class ReviewDeleteView(PermissionRequiredMixin, DeleteView):
    permission_required = "webapp.change_review"
    model = Review

    def get(self, request, *args, **kwargs):
        return self.delete(request, *args, **kwargs)

    def has_permission(self):
        return super().has_permission() or self.get_object().author == self.request.user

    def get_success_url(self):
        return reverse("webapp:product_view", kwargs={"pk": self.object.product.pk})


class NotModeratedReview(PermissionRequiredMixin, ListView):
    queryset = Review.objects.filter(is_moderated=False)
    context_object_name = "reviews"
    template_name = "reviews/not_moderated.html"
    ordering = ['-updated_at']
    permission_required = "webapp.review_not_moderated"

source/webapp/templates/products/create.html
{% extends "base.html" %}

{% block title %}
    Добавить товар
{% endblock %}

{% block content %}
    <div class="text-center">
        <h1>Добавить товар</h1>
        <form action="" method="post" enctype="multipart/form-data">
            {% include "partial/form.html" with button_text="Добавить" %}
        </form>
    </div>
{% endblock %}

source/webapp/templates/products/delete.html
{% extends "base.html" %}

{% block title %}
    Удалить Товар
{% endblock %}

{% block content %}
    <h2>Вы действительно хотите удалить товар {{ product.name }}?</h2>
    <form action="" method="post">
        {% csrf_token %}
        <button class="btn" type="submit">Да</button>
    </form>
    <a class="btn" href="{% url "webapp:product_view" product.pk %}">Нет</a>
{% endblock %}

source/webapp/templates/products/detail.html
{% extends "base.html" %}
{% load static %}

{% block nav %}
    {% if perms.webapp.change_product %}
        <li class="nav-item">
            <a class="nav-link" href="{% url "webapp:update_product" product.pk %}">Редактировать</a>
        </li>
    {% endif %}

    {% if perms.webapp.delete_product %}
        <li class="nav-item">
            <a class="nav-link" href="{% url "webapp:delete_product" product.pk %}">Удалить</a>
        </li>
    {% endif %}
        {% if request.user.is_authenticated %}
        <li class="nav-item">
            <a class="nav-link" href="{% url "webapp:review_create" product.pk %}">Добавить отзыв</a>
        </li>
        {% endif %}
{% endblock %}

{% block content %}
    <div class="card mt-3">
        <div class="card-body text-center">
            <h5 class="card-title">{{ product.name }} | {{ product.get_avg_mark|default_if_none:0 }}</h5>
            <h6 class="card-subtitle mb-2 text-muted">Категория товара: {{ product.category }}</h6>
            <p class="card-text">{{ article.description }}</p>
            {% if product.picture %}
                <img src="{{ product.picture.url }}" alt="#">
            {% else %}
                <img src="{% static "images/no_photo.jpg" %}" alt="">
            {% endif %}

        </div>
    </div>
    {% include "partial/reviews_list.html" %}
{% endblock %}

source/webapp/templates/products/index.html
{% extends "base.html" %}
{% load static %}

{% block nav %}
    {% if perms.webapp.add_product %}
        <li class="nav-item">
            <a class="nav-link" href="{% url "webapp:create_product" %}">Добавить Товар</a>
        </li>
    {% endif %}
    {% if perms.webapp.review_not_moderated %}
        <li class="nav-item">
            <a class="nav-link" href="{% url "webapp:not_moderated_reviews" %}">Немодерированные отзывы</a>
        </li>
    {% endif %}
{% endblock %}

{% block content %}
    <h1 class="text-center">Товары</h1>
    <div class="row">
        {% for product in products %}
            <div class="col-12 col-md-6 col-lg-4">
                <div class="card mb-3">
                    <div class="card-body">
                        <h5 class="card-title">{{ product.name }} | {{ product.get_avg_mark|default_if_none:0 }}</h5>
                        <p>{{ product.category }}</p>
                    </div>
                    <a href="{% url "webapp:product_view" product.pk %}" class="card-link btn btn-primary">Подробнее</a>
                </div>
            </div>
        {% empty %}
        {% endfor %}
        {% if is_paginated %}
            <div class="text-center">{% include "partial/pagination.html" %}</div>
        {% endif %}
    </div>
{% endblock %}

source/webapp/templates/products/update.html
{% extends "base.html" %}

{% block title %}
    Редактировать Товар
{% endblock %}

{% block content %}
    <div class="text-center">
        <h1>Редактировать Товар</h1>
        <form action="" method="post">
            {% include "partial/form.html" with button_text="Редактировать" %}
        </form>
    </div>
{% endblock %}